---
abstract: 'Automatically convert POD to a README in any format for Dist::Zilla'
author:
  - 'Ryan C. Thompson <rct@thompsonclan.org>'
  - 'Karen Etheridge <ether@cpan.org>'
build_requires:
  Carp: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::DZil: 0
  Test::Deep: 0
  Test::Fatal: 0
  Test::More: 0.94
  Test::Most: 0
  Test::Requires: 0
  autodie: 0
  lib: 0
  perl: 5.008
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ReadmeAnyFromPod
no_index:
  directory:
    - corpus
requires:
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::AfterBuild: 0
  Dist::Zilla::Role::AfterRelease: 0
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::FileMunger: 0
  Dist::Zilla::Role::FilePruner: 0
  Dist::Zilla::Role::FileWatcher: 0
  Encode: 0
  IO::Handle: 0
  IO::Scalar: 0
  List::Util: 0
  Moose: 0
  Moose::Autobox: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Has::Sugar: 0
  PPI::Document: 0
  Path::Tiny: 0.004
  Pod::Markdown: 0
  Pod::Simple::HTML: 3.23
  Pod::Simple::Text: 3.23
  Scalar::Util: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/DarwinAwardWinner/Dist-Zilla-Plugin-ReadmeAnyFromPod
  repository: https://github.com/DarwinAwardWinner/Dist-Zilla-Plugin-ReadmeAnyFromPod.git
version: 0.142470
